CREATE TABLE `betaLeads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` varchar(24) NOT NULL,
	`firstName` varchar(120) NOT NULL,
	`email` varchar(320) NOT NULL,
	`location` varchar(120) NOT NULL,
	`sourceType` enum('community','content','referral','outbound','direct','other') NOT NULL DEFAULT 'direct',
	`sourceDetail` text,
	`currentStatus` enum('new','reviewed','qualified','invited','responded','activated','nurture','inactive','referred','lost') NOT NULL DEFAULT 'new',
	`fitScore` enum('high','medium','low') NOT NULL,
	`coupleConfirmed` boolean NOT NULL,
	`priorities` json NOT NULL,
	`urgencyLevel` enum('low','medium','high') NOT NULL,
	`betaOpenness` enum('yes','maybe','no') NOT NULL,
	`callOpenness` enum('yes','maybe','no') NOT NULL,
	`hardestRightNow` text NOT NULL,
	`notes` text,
	`nextAction` text NOT NULL,
	`nextActionDueAt` bigint,
	`lastTouchAt` bigint,
	`outcome` enum('invited','activated','inactive','referred','lost','pending') NOT NULL DEFAULT 'pending',
	`createdAtMs` bigint NOT NULL,
	`updatedAtMs` bigint NOT NULL,
	CONSTRAINT `betaLeads_id` PRIMARY KEY(`id`),
	CONSTRAINT `betaLeads_leadId_unique` UNIQUE(`leadId`)
);
--> statement-breakpoint
CREATE TABLE `sharedPlans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`planId` varchar(24) NOT NULL,
	`leadId` varchar(24) NOT NULL,
	`primaryRecommendation` enum('emergency_savings','debt_payoff','home_deposit','long_term_investing') NOT NULL,
	`secondaryRecommendation` enum('emergency_savings','debt_payoff','home_deposit','long_term_investing'),
	`realismScore` decimal(3,1) NOT NULL,
	`sustainabilityScore` decimal(3,1) NOT NULL,
	`fairnessScore` decimal(3,1) NOT NULL,
	`summary` text NOT NULL,
	`monthlyCommitment` text NOT NULL,
	`monthlyCommitmentAmount` decimal(10,2) NOT NULL,
	`reviewPrompt` text NOT NULL,
	`plannerInputs` json NOT NULL,
	`plannerOutput` json NOT NULL,
	`monthlyReviewCount` int NOT NULL DEFAULT 0,
	`lastReviewedAtMs` bigint,
	`createdAtMs` bigint NOT NULL,
	`updatedAtMs` bigint NOT NULL,
	CONSTRAINT `sharedPlans_id` PRIMARY KEY(`id`),
	CONSTRAINT `sharedPlans_planId_unique` UNIQUE(`planId`)
);
